spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          filters:
            - name: ResponseTimeMeter
              args:
                monitorUrl:
                  - "/foo"
                  - "/bar"

server:
  port: 10000

